# Generated by Django 3.1 on 2020-09-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedGraphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphs_count', models.BigIntegerField(default=0, verbose_name='generated graphs count')),
            ],
        ),
    ]
